### ISSUE TITLE
Mismatch between definition and access of `min-mapping-quality`

### ISSUE THREAD

**Issue by claymcleod** [zaeleus/squab#3]
Tried to use the latest version of `squab quantify` today and I got this issue. I was able to trace 

```bash
$ squab quantify --output results.txt --annotations gencode.v41.annotation.gff3 $PATH_TO_BAM
thread 'main' panicked at 'Mismatch between definition and access of `min-mapping-quality`. Could not downcast to TypeId { t: _ }, need to downcast to TypeId { t: _ }
```

I was able to trace this back, it appears the issue was introduced in this commit: https://github.com/zaeleus/squab/commit/4c24e8bb9193d20265d8be40c411801be2fe957b. Do you get this when trying to run `squab quantify`

**Comment by zaeleus** [comment]
Thanks, this threw an error for me as well. It was indeed just a type mismatch at runtime.
